### 帮助文档 https://segmentfault.com/a/1190000016300254
### 变量
@host = http://localhost:8080
@json = Content-Type: application/json
@form = application/x-www-form-urlencoded
@token = eyJhcHBJZCI6IioiLCJleHBpcmVkQXQiOiIxNTgxNzU1MjAzNTA5IiwiaWQiOiIxIiwibmlja25hbWUiOiLns7vnu5_nrqHnkIblkZgiLCJyb2xlcyI6IltcIlJPTEVfQURNSU5fU1lTVEVNXCJdIiwic2lnbmVkQXQiOiIxNTc5MTYzMjAzNTEwIiwidXNlcm5hbWUiOiJhZG1pbiJ9.58168d0289d754dbd9b75936eeb96805

### 机构
GET {{host}}/api/orgs

### 登录
POST {{host}}/api/login/tokens
Content-Type: application/x-www-form-urlencoded

username=admin&password=admin

### 注销
GET {{host}}/logout

### 当前用户
GET {{host}}/api/login/users/current
auth-token: {{token}}

### Patch 更新用户信息
POST {{host}}/api/users/1
Content-Type: application/x-www-form-urlencoded

gender=1&_method=PATCH

### 页面异常
GET {{host}}/api/demo/exception
X-Requested-With: XMLHttpRequest

### Converter
GET {{host}}/api/demo/string2date?date=2020-01-01

### POST 中文
POST {{host}}/api/demo/encoding
Content-Type: application/x-www-form-urlencoded

name=中文字符串

############################################### 任务调度

### 创建 Job
POST http://localhost:8090/api/jobs
X-Requested-With: XMLHttpRequest

### Job 执行准备
POST http://localhost:8080/api/jobs/1/prepare
X-Requested-With: XMLHttpRequest

### 执行 Job
POST http://localhost:8090/api/jobs/1/executions/1596167137391/execute
X-Requested-With: XMLHttpRequest

### 参数异常
GET http://localhost:8080/api/demo/invalid
X-Requested-With: XMLHttpRequest
