### 帮助文档 https://segmentfault.com/a/1190000016300254
### 变量
@host = http://localhost:8080
@json = Content-Type: application/json
@form = application/x-www-form-urlencoded

### 机构
GET {{host}}/api/orgs

### 登录
POST {{host}}/api/login/tokens
Content-Type: application/x-www-form-urlencoded

username=admin&password=admin

### 注销
GET {{host}}/logout

### 当前用户
GET {{host}}/api/login/users/current
auth-token: eyJhcHBJZCI6IioiLCJleHBpcmVkQXQiOiIxNTgxNzU1MjAzNTA5IiwiaWQiOiIxIiwibmlja25hbWUiOiLns7vnu5_nrqHnkIblkZgiLCJyb2xlcyI6IltcIlJPTEVfQURNSU5fU1lTVEVNXCJdIiwic2lnbmVkQXQiOiIxNTc5MTYzMjAzNTEwIiwidXNlcm5hbWUiOiJhZG1pbiJ9.58168d0289d754dbd9b75936eeb96805

### Patch 更新用户信息
POST {{host}}/api/users/1
Content-Type: application/x-www-form-urlencoded

gender=1&_method=PATCH

### 页面异常
GET {{host}}/api/demo/exception
X-Requested-With: XMLHttpRequest

### Converter
GET {{host}}/api/demo/string2date?date=2020-01-01
